spring.application.name=salary

spring.profiles.include=jelly
spring.profiles.active=jelly

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ??? API ??
naver.api.client-id=${NAVER_CLIENT_ID}
naver.api.client-secret=${NAVER_CLIENT_SECRET}
