spring.application.name=salary

spring.profiles.include=jelly
spring.profiles.active=jelly

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Base URL
app.base.url=https://api.ssalary.shop
# ??? API ??
#naver.api.client-id=HNUu5z_F22Y1iUsErnmB
#naver.api.client-secret=hr5lt2VowV